### ISSUE TITLE
Better Error message if Code Coverage Profile is Not Registered

### ISSUE THREAD

**Issue by jacobaloysious** [OpenCover/opencover#163]
> No results - no assemblies that matched the supplied filter were instrumented
>      [exec]     this could be due to missing PDBs for the assemblies that match the filter
>      [exec]     please review the output file and refer to the Usage guide (Usage.rtf)

I was pretty struck with the above error message and I was fiddling around with the `Filters` and `.pdb`location. It took hours before we could realize the issue could be because of `Code Coverage Profile` is `Not Registered`

But yes adding `-register:user` to the command line fixed the issue.

I just felt if the Error Message could have hinted me on this, it could have saved hours..

**Comment by ankurpr** [comment]
Hi..
I am not using Opencover , Reportgenerator and NUnit instead of batch file but getting the same error as,
> Committing...
> No results, this could be for a number of reasons. The most common reasons are:
>     1) missing PDBs for the assemblies that match the filter please review the
>     output file and refer to the Usage guide (Usage.rtf) about filters.
>     2) the profiler may not be registered correctly, please refer to the Usage
>     guide and the -register switch.

As you said by adding _-register:user_ it will work. So, in my case how where i should add this?
![screenshot 229](https://cloud.githubusercontent.com/assets/24837829/21560833/b9ed11c4-ce8a-11e6-89b3-f0afa3f666ea.png)

**Comment by sawilde** [comment]
@ankurpr - on the command line for OpenCover - please read the documentation.
