### ISSUE TITLE
Line indicated as uncovered when in fact it is

### ISSUE THREAD

**Issue by Jericho** [OpenCover/opencover#219]
What does it mean when OpenCover+ReportGenerator generate a report that looks like this:

http://screencast.com/t/MJn8A66zh

As you can see, that line 55 is highlighted in red which indicates I haven't covered it. However, this does not make sense to me since line 57 and 58 are covered.

**Comment by calimero1000582** [comment]
I have a few files where closing brace considered as not tested
![image](https://user-images.githubusercontent.com/3637661/53642823-9e005800-3c00-11e9-856b-6f758038ca75.png)

There is 8 space before the closing brace

In OpenCover.xml, for this file, I have
```xml
<SequencePoint vc="0" uspid="11514" ordinal="8" offset="317" sl="502" sc="9" el="502" ec="10" bec="0" bev="0" fileid="1003" />
```

**Comment by sawilde** [comment]
The data come from the PDB and OpenCover puts an instrument point at the indicated location in the IL `offset="317"` it it doesn't get hit - it doesn't get hit.

If you have source code that replicates the problem you are seeing then we can hopefully investigate further.

Please raise it is an new issue though rather than hijack this one - thanks
