### ISSUE TITLE
Support Microsoft Fakes

### ISSUE THREAD

**Issue by kariabancroft** [OpenCover/opencover#256]
We are attempting to run Open Cover with VSTest on Tests that are utilizing Microsoft Fakes. We confirmed that the test project showed coverage successfully prior to adding in the fakes. Once we started running with the fakes our results show zero coverage for all metrics. 

Test Run Successful.
Test execution time: 36.2565 Seconds
Committing...
Visited Classes 0 of 54 (0)
Visited Methods 0 of 425 (0)
Visited Points 0 of 3652 (0)
Visited Branches 0 of 497 (0)

==== Alternative Results (includes all methods including those without corresponding source) ====
Alternative Visited Classes 0 of 64 (0)
Alternative Visited Methods 0 of 487 (0)

We found this post on Twitter (https://twitter.com/japj/status/460743524892549120) which potentially shows that someone else has confirmed the zero coverage when using Fakes.

Guessing that this might have to do with the chaining issue mentioned related to Mole, but was wondering if we could look into it further.

**Comment by sawilde** [comment]
Moles used CLRMONITOR_EXTERNAL_PROFILERS environment variable to chain on to OpenCover e.g.

    set CLRMONITOR_EXTERNAL_PROFILERS={1542C21D-80C3-45E6-A56C-A9C1E4BEB7B8}

see https://github.com/OpenCover/opencover/issues/63 and https://github.com/OpenCover/opencover/issues/109

I suspect the same should work for Fakes

you may also need to manually register the OpenCover profilers (x86/x64) using regsvr32 and omit the `-register` switch when running OpenCover (as it is already registered).

**Comment by sawilde** [comment]
However I can't get it to work (like I could with Moles) so perhaps things have since changed; MS have their own code coverage utility so they may no longer allow chaining to 3rd parties like OpenCover

Looking at the event logs it looks like the `vstest.console.exe` registers its own profiler (so it can rewrite the code for shim/stubs) and gets the runtime to load that instead of the OpenCover profiler - so it would be necessary to get MS to chain from Fakes=>OpenCover like they used to with Moles.

**Comment by molnargab** [comment]
From [this doc](http://msdn.microsoft.com/en-us/library/hh708916.aspx) it seems Fakes does the instrumentation at compile time. So it should mean that we have the corresponding PDBs as well. I guess it's almost the same output if, for some reason, OpenCover is not able to load the PDBs.

Though it would be worth to decompile the actual code (with ILSpy) or even check the PDB refernces with `ildasm`.

Perhaps we could start with some easier examples first to check if anything is working at all (though these may be a similar use-case), e.g.
* a test on some shim,
* a test on a class using a shim,
* a test on stubbing e.g. System.DateTime.

If it's indeed done with the Profiling API, I wonder if it's possible for us to mimic what Moles did, e.g. OpenCover attaches itself, and will forward calls to Fakes (or Fakes will just overwrite our registration).

**Comment by sawilde** [comment]
Yes it creates the `Fake` assemblies at compile time but when it runs you see it register and use it's own profiler i.e. it overwrites the environment variables that the runtime uses to determine which profiler to load. As such the OpenCover profiler is loaded initially when the runner analyses the test assemblies (so we get details) but then runner changes the environment variable when it launches/executes the actual tests the `Microsoft.IntelliTrace.Profiler.11.0.0.dll` is loaded instead - you can see this in the eventlog.

Since we can't rewrite the IntelliTrace profiler to forward requests we would have to get the OpenCover profiler to load instead of the IntelliTrace one and forward requests and that the OpenCover and IntelliTrace rewriting (suspected) do not interfere with each other.

I also see that NCrunch are working with Fakes - http://stackoverflow.com/questions/19385037/microsoft-fakes-wont-run-in-normal-unit-test-contexts
so perhaps there is an alternative way that could be investigated or enquired about.

**Comment by sawilde** [comment]
I've made a prelim enquiry to the MSDN forums - https://social.msdn.microsoft.com/Forums/en-US/3ed81407-4d72-42e9-bd1d-5c241e0ce7bf/running-fakes-with-3rd-party-coverage-tools?forum=vsunittest

**Comment by sawilde** [comment]
Thankfully we are still supported by TypeMock (for those that use it). I have personally avoided these testing tools as I have found that in the wrong hands they cause more harm than good and create poor design - though I do see why people working with legacy code may need them when trying to write tests for code that was not written with testing in mind; so I have them in my arsenal but thankfully not had to fire. 

I have wondered in the past if we should look at building an open source version of this sort of mocking framework even if the only thing it handled was DateTime.Now and DateTime.UtcNow; the two methods that cause me the most grief in Unit Testing but even then I can quickly work around it by injecting a `IWrappedDateTime` implementation and using Moq or NSubstitute (and others) if I really need to.

**Comment by sawilde** [comment]
Okay no feedback on my queries - other than MS Support saying support for 3rd party tools is not covered in their remit - which is sort of what I expected. 

So now we have to decide do we want OpenCover to support Fakes?

We could as proposed load the Fakes profiler ourseleves `-supportfakes` and prevent fakes from trying to register their profiler; it's tricky. It would mean having to work out what parts of the profiler API fakes is trying to use and ensuring that we pass that information through our profiler adding our needs on the way. I have code somewhere I can use to spike an investigation into the needs of the fakes profiler. I think I may put it in another repository to keep this one clean from such investigation spikes and if it is viable when can integrate the code - if anyone is interested in getting involved let me know and we can collaborate.

**Comment by sawilde** [comment]
FYI: The fakes profiler wants the following events from the runtime

    DWORD expected = COR_PRF_DISABLE_ALL_NGEN_IMAGES;
	expected |= COR_PRF_DISABLE_TRANSPARENCY_CHECKS_UNDER_FULL_TRUST;
	expected |= COR_PRF_DISABLE_INLINING;
	expected |= COR_PRF_MONITOR_THREADS;
	expected |= COR_PRF_MONITOR_JIT_COMPILATION;
	expected |= COR_PRF_MONITOR_APPDOMAIN_LOADS;
	expected |= COR_PRF_MONITOR_ASSEMBLY_LOADS;
	expected |= COR_PRF_MONITOR_MODULE_LOADS;

These should be compatible with the OpenCover ones - the biggest challenge will be around JITting of the same methods when/if that happens.

**Comment by sawilde** [comment]
my progress so far https://github.com/sawilde/fakesinvestigation

**Comment by sawilde** [comment]
Well the spike went well - I have merged in my spike - I have only tested a simple Shim (DateTime) but the two profilers work well together within that simple exercise - I suspected they might as Moles worked fine.

**Comment by sawilde** [comment]
For anyone brave enough to try - you can use these builds

https://ci.appveyor.com/project/sawilde/opencover-954/build/artifacts

**Comment by sawilde** [comment]
What we have only works for VS2013 version of Microsoft.Fakes - will need to do more work on VS2012 and VS2015 versions - of course everytime MS makes a release we may have to rework the instrumentation issue in order to intercept the profiler and ensure our hooks work.

**Comment by sawilde** [comment]
Currently if what you are shimming is also what you are covering we only currently record a visited method but not any other coverage. This is due to both profilers instrumenting the same method - I am hoping to resolve this by changing the order of instrumentation as I believe that MS insert their trampoline at the beginning and return control back to the method if it hasn't been shimmed (that is what I would have done) so I am hoping OpenCover can instrument first and then let the Fakes profiler do its instrumentation (fingers crossed). If that doesn't work I am going to see if I the Fakes profiler updates the codemap so I an use that to determine the new offsets for instrumenting; alternatively I can use the host to provide me with the expected IL and use that to find the start of where we should actually start instrumenting.

**Comment by sawilde** [comment]
@kariabancroft - have you tried out the fakes support yet?

**Comment by sawilde** [comment]
released as of http://www.nuget.org/packages/OpenCover/4.5.3723

**Comment by rotparmna** [comment]
@sawilde I need to install on a server with support for OpenCover Fakes, but the 3522 version, according to historical changes do not have the support, when it will release a version with support for Fakes?

It is to install on a server with Jenkins.

Thanks

**Comment by sawilde** [comment]
you can download the msi and zip directly from the build servers

https://ci.appveyor.com/project/sawilde/opencover/build/1.0.75/artifacts

sorry not managed to integrate github publishing yet of release builds (we have nuget integration)

**Comment by rotparmna** [comment]
@sawilde thank you very much for your answer.

Install the release you indicate to me, but I get the following error "UnitTestIsolation instrumentation failed to initialize. Please restart Visual Studio and rerun esta test", you know it can be?

Thanks

**Comment by sawilde** [comment]
Sorry I don't - if you have a sample that replicates it then I may be able to help.
