### ISSUE TITLE
Problems with profiling apps that launch processes

### ISSUE THREAD

**Issue by stephentoub** [OpenCover/opencover#274]
Are there any known issues when the app having coverage profiled launches other managed processes?

The CoreFX System.Diagnostics.Process tests (https://github.com/dotnet/corefx/tree/7116584186f8f3a886616aaf8cb5d4a982c60e27/src/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests) currently have code coverage disabled because, when coverage is enabled, the testing hangs.  I just looked into it briefly, and it appears that after the tests finish running, OpenCover is running an infinite loop in SaveVisitData:
https://github.com/OpenCover/opencover/blob/b7ae4a48ae788914a57de0937a02e113a92f40c2/main/OpenCover.Framework/Manager/ProfilerManager.cs#L141

These tests launch a bunch of processes that are themselves managed apps, and because they inherit the environment variables from the parent process, the profiler is also getting hooked up to them.  I'm guessing there's then some sort of issue where the host wasn't expecting data to come in from multiple profiled apps, but I've not explored the OpenCover code for this.

**Comment by sawilde** [comment]
OpenCover should handle multiple processes otherwise there is no why we can handle nunit or mstest (vstest) as they call multiple processes in order to execute their tests. There may however be a limit on the number it can handle (I've never experimented) do you have a figure that triggers the issue?

How long is it hanging for?

To stop waiting for data the profiler waits for each process to close - sometimes however the runtime does not close cleanly and we do not get a Shutdown message.

Eventually the initial process [shutsdown](https://github.com/OpenCover/opencover/blob/b7ae4a48ae788914a57de0937a02e113a92f40c2/main/OpenCover.Framework/Manager/ProfilerManager.cs#L168) and we start to tidy up eventually leading us to add an [empty message to the queue](https://github.com/OpenCover/opencover/blob/b7ae4a48ae788914a57de0937a02e113a92f40c2/main/OpenCover.Framework/Manager/ProfilerManager.cs#L206)

If you have a simple repeatable test that we can investigate with - awesome.

**Comment by stephentoub** [comment]
Thanks, @sawilde, and for the additional info.

> How long is it hanging for?

Indefinitely.

> If you have a simple repeatable test that we can investigate with - awesome

Repro steps:
1. git clone http://github.com/dotnet/corefx
2. cd corefx
3. build
That'll make sure all of the NuGet packages have been downloaded, everything's working correctly, etc.  Then
4. cd src\System.Diagnostics.Process\tests\System.Diagnostics.Process.Tests
5. Remove the ```<CoverageEnabledForProject>false</CoverageEnabledForProject>``` attribute from System.Diagnostics.Process.Tests.csproj  (the false value is currently disabling the coverage): https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Process/tests/System.Diagnostics.Process.Tests/System.Diagnostics.Process.Tests.csproj#L12
6. build /t:BuildAndTest /p:Coverage=true
That'll build and then invoke OpenCover for just this set of xunit tests.

When I do the above, I see the process tests finish, with xunit printing out the summary, and then it just sits waiting, whereas normally OpenCover at this point would print out its processing results.  When I look at Task Manager, I see OpenCover pegging a CPU indefinitely, and I don't see any of the ProcessConsole_TestApp processes still running.  And when I attach a profiler, I see OpenCover just spinning in the mentioned location.

**Comment by sawilde** [comment]
thanks - I'll have a look

**Comment by stephentoub** [comment]
Thanks for the fix, Shaun.
