### ISSUE TITLE
3 of 4 branches are covered

### ISSUE THREAD

**Issue by Jericho** [OpenCover/opencover#292]
I have the following code:
```
else if (statusCode >= 500 && statusCode < 600)
{
	var errorMessage = string.Format("Received a server ({0}) error from {1}", (int)response.StatusCode, request.Resource);
	throw new HttpException(errorMessage, response.StatusCode, responseUri);
}
```
Looking at the compiled DLL with ILSpy, I see 
```
else
{
	string errorMessage;
	if (statusCode >= 500 && statusCode < 600)
	{
		errorMessage = string.Format("Received a server ({0}) error from {1}", (int)response.StatusCode, request.Resource);
		throw new HttpException(errorMessage, response.StatusCode, responseUri);
	}
}
```
When I run OpenCover (4.5.3723) + ReportGenerator (2.1.4.0) I get an indicator next to the "else if" that says "3 of 4 branches are covered". I have a unit test with a statusCode less than 500, another one where the statusCode is between 500 and 599 and finally another unit test with a statusCode larger than 599 but I fail to see the 4th situation.

Any ideas?

**Comment by sawilde** [comment]
In your scenario you have

````
| data | sc >= 500 | sc < 600 |
| 499  | F         | T        |
| 550  | T         | T        |
| 601  | T         | F        | 
````

so the scenario it is looking for is when both are F - which of course is not possible because of 
a) no such number exists
b) because even if such a number did exist the use of the logical `&&`, which will not evaluate the 2nd condition if the 1st is false

**Comment by sawilde** [comment]
OpenCover only knows of the IL produced - it does not know the source code behind it and so makes no assumptions about how you have structured your code.

**Comment by Jericho** [comment]
You have to admit it's weird to be told that I am covering 3 out of 4 branches when in fact the 4th branch is not logically possible!

In fact, wouldn't it be reasonable for OpenCover to consider "false && false" to be an impossible scenario and therefore there should only be 3 branches to cover? I think it would apply to any scenario where you have a "if" statement with two or more conditions.

**Comment by molnargab** [comment]
I've tried to reproduce the issue but it seems these 3 cases you had (i.e. 499, 501, 601) do cover all the branch points. 

Could you check the relevant part of your output xml? It should show you the IL offset of the branching instruction and the fact it's uncovered (`vc=0`).

**Comment by sawilde** [comment]
> In fact, wouldn't it be reasonable for OpenCover to consider "false && false" to be an impossible scenario and therefore there should only be 3 branches to cover? I think it would apply to any scenario where you have a "if" statement with two or more conditions.

I understand where you are coming from but as I mentioned before OpenCover only looks at the IL and not the source code; in order to maintain performance it is rather dumb in that it blindly instruments the code and results and leaves it to more intelligent beings to interpret the results.

To do what you want would require a lot of analysis on the code to determine that the two conditions were working against the same variable(s) and that one of the branch paths is impossible. You think this is simple for a single variable, now imagine what it would be like for say 5 variables with multiple `&&` and `||` operators with many different types (not just value types) - it is a slippery slope and something I'll leave to the commercial tool vendors (and researchers) looking for that one killer feature over the competition.

Like @molngarb I also replicated you issue and all branch paths were executed, however you must remember these are IL branches not source code branches and so it all depends on what IL was produced for your source code.

e.g.

    public static void Test(int x)
    {
        if (x >= 500 && x < 600)
        {
            Console.WriteLine("Success");
        }
    }

produced

        IL_0000: nop
	IL_0001: ldarg.0
	IL_0002: ldc.i4 500
	IL_0007: blt.s IL_0016

	IL_0009: ldarg.0
	IL_000a: ldc.i4 600
	IL_000f: clt
	IL_0011: ldc.i4.0
	IL_0012: ceq
	IL_0014: br.s IL_0017

	IL_0016: ldc.i4.1

	IL_0017: nop
	IL_0018: stloc.0
	IL_0019: ldloc.0
	IL_001a: brtrue.s IL_0029

	IL_001c: nop
	IL_001d: ldstr "Success"
	IL_0022: call void [mscorlib]System.Console::WriteLine(string)
	IL_0027: nop
	IL_0028: nop

	IL_0029: ret

and for the 3 tests I created I got 100% branch coverage so it is down to the IL that is produced - your IL is probably different to ours.

I know leave you with the same code but implemented very differently

    public static void Test(int x)
    {
        if (x < 500) 
            return;
        if (x < 600)
        {
            Console.WriteLine("Success");
        }
    }

this one which after decompiling in IL spy looks like

    public static void Test(int x)
    {
        if (x >= 500)
        {
	    if (x < 600)
            {
                Console.WriteLine("Success");
            }
        }
    }

weird huh!
