### ISSUE TITLE
Coverage of lambda

### ISSUE THREAD

**Issue by dfev77** [OpenCover/opencover#302]
I have a test code using a lambda

```csharp
meta.ColumnInfos.First(col => col.ColumnName == "ColumnWithInitialization")
```

And the compiler seems to create a static Func for the lambda and sets it only once. Actual method looks like (copied from dotPeek)
```csharp
if (className.CS\u0024\u003C\u003E9__CachedAnonymousMethodDelegate3 == null)
{
  // ISSUE: method pointer
  className.CS\u0024\u003C\u003E9__CachedAnonymousMethodDelegate3 = new Func<ColumnMetadata, bool>((object) null, __methodptr(\u003CGetColumnExistsQuery_ForColumnWithInitializationScript_ThisIsUsedInQuery\u003Eb__2));
}
```

and in the coverage report, of course this does not have a 100% branch coverage.

And the question would be: would it make sense to have OpenCover "hack" the coverage for such cases and consider for the compiler generated as 100% covered? 

Is quite likely to introduce other issues but it could also allow to exclude cases (when inspecting coverage report) where you actually don't have proper code branch coverage.

**Comment by sawilde** [comment]
> And the question would be: would it make sense to have OpenCover "hack" the coverage for such cases and consider for the compiler generated as 100% covered?

Perhaps - but currently for speed OpenCover tries not to make any judgements about your code, as it only sees the final IL, other than where the sequence points are (PDB) and what branches it should instrument (IL). 

The trick here is determining when the IL is the way it is because of the syntax you have described and not because someone has actually written the code in such a way to produce the same IL, without impacting on the instrumentation. Could it be done probably but I like to leave the report as raw as possible and leave these things to those interpreting the report e.g. presenting it in HTML etc.

**Comment by molnargab** [comment]
Statement coverage of the test code is a good indicator whether you've missed to add a `[Test]` attribute for a test case. But I don't see the meaning of checking if all branches of the tests was executed. 

Generally tests should be as simple as possible (so that they could be easily read and understood, and they won't have bugs). This way you don't really need to have any braches in the test code to check if they are all executed or not. The only exception I can think of may be parameterized test cases, where you may need some logic in the test itself e.g. to set up expected exceptions conditionally.

If the goal is indeed to have 100% branch coverage in your test code, you could extract creating the lambda into a new method, and create your own exclusion attribute (let's say `ExcludedLambdasAttribute`). Something like:
```c#
[Test]
public void TestMethod()
{
  meta.ColumnInfos.First(WhereColumnNameEquals("ColumnWithInitialization"));
}

[ExcludedLambdas]
private Func<ColumnInfo, bool> WhereColumnNameEquals(string columnName)
{
    col => col.ColumnName == columnName;
}
```

See [Usage](https://github.com/OpenCover/opencover/wiki/Usage#optional-arguments) for more.

**Comment by sawilde** [comment]
It may be worth investigating if it is possible to ignore these assignments but only is there is a reliable way of identifiying them.

**Comment by dfev77** [comment]
Just to clear it up.
The porpose is not to have coverage of tests but of the code under test,
which might also use lambda and so show lower branch coverage.
And, as 100% statement coverage does not mean you have covered all relevant
cases, you might also want this "as high as possible". And don't want to
waiste time looking through the code and coverage report just to see that a
few lambas give you low branch coverage.

So yes, it goes down to figuring out if this can be handled at the point of
generating the coverage data or as other stated at generating the report
out of that.

Hope to be able to look into the report generation, to see of this can
handled.

Thanks,
Florin

**Comment by molnargab** [comment]
Seems PDBs won't help us in this case, I barely see anything marked as compiler generated in the IL for lambdas.

**Comment by sawilde** [comment]
I've added a way to skip these branches using a pattern of instructions - this is currently the only pattern I have added so far (release/debug variations)
