### ISSUE TITLE
Feature: Flag to return a different error level when an underlying unit test fails

### ISSUE THREAD

**Issue by dpnkarthik** [OpenCover/opencover#311]
It would be good to have a flag to that returns a different exit code whenever an underlying unit test fails. It would help to integrate code coverage report to the build process.

**Comment by sawilde** [comment]
OpenCover does not run your tests the test runner does. If your test runner returns an errorcode then this will be returned as part of OpenCover's return code - see [Usage](https://github.com/OpenCover/opencover/wiki/Usage)

`-returntargetcode[:<opencoverreturncodeoffset>]` - Return the target process return code instead of the OpenCover console return code. Use the offset to return the OpenCover console at a value outside the range returned by the target process.
