### ISSUE TITLE
OpenCover.Console.exe does not return non-zero error code when target returns non-zero

### ISSUE THREAD

**Issue by KevM** [OpenCover/opencover#333]
Our build when running coverage reports with failing tests returning a success result (zero). This is causing our build automation to have false positives. e.g. Tests fail but OpenCover does not report them so the build automation continues. 

I used these two batch files to confirm that `OpenCover.Console.exe` is always returning zero. The target executable is returning a result of *9*.

### exit9.bat

Simple batch file that returns a positive error.

```bat
EXIT /B 9
```
### test.bat

This runs open cover console with a batch file. No matter what the result code of the batch file the Console returns a zero error code. 

```bat
(
.\packages\OpenCover\tools\OpenCover.Console.exe -target:".\exit9.bat" -output:"./TestResults/opencover-results.xml" -filter:"+[*]* -[*Tests]* -[Moq.AutoMock]*""

  ECHO %errorlevel%
  
  set foundErr=1
  if errorlevel 0 if not errorlevel 1 set "foundErr="
  if defined foundErr echo errorlevel is non-zero
)
```

**Comment by sawilde** [comment]
In the [Usage](https://github.com/OpenCover/opencover/wiki/Usage) section of the wiki and the supplied docs you will see that there is an option to deal with this.

`-returntargetcode[:<opencoverreturncodeoffset>]` - Return the target process return code instead of the OpenCover console return code. Use the offset to return the OpenCover console at a value outside the range returned by the target process.

**Comment by KevM** [comment]
Thanks for the help. I have this queued up to tryout.

**Comment by KevM** [comment]
Confirmed that adding `-returntargetcode` not makes OpenCover console return non-zero error codes.
