### ISSUE TITLE
Add option to instrument entire assemblies in-place

### ISSUE THREAD

**Issue by kzu** [OpenCover/opencover#393]
Currently, OpenCover works exclusively by leveraging the CLR run-time profiling interfaces. This has limitations, as shown on issue #368 which involves cross-process remoting calls. It also makes it impossible to use OpenCover on anything than the Windows .NET CLR, since the profiling APIs are unmanaged COM interfaces unavailable on Mono or even CoreCLR (as of now at least, as noted on dotnet/coreclr#445). 

In-place instrumentation, like [Visual Studio's VSInstr.exe](https://msdn.microsoft.com/en-us/library/ms182402.aspx), would avoid this problem altogether by modifying the entire assemblies, and then running whatever you need to run normally. A collector process is started and shut down at the end of the run, and it receives the callbacks from the instrumented code appropriately. There's a walkthrough of how this [works from a command line](http://blogs.msdn.com/b/ianhu/archive/2005/11/15/493110.aspx).

Hopefully a big chunk of what OpenCover already does could be re-purposed to support this.

This new option would mean OpenCover could work on any platform that can run the instrumented assemblies (presumably even Xamarin), as long as the collector can receive the callbacks (again, this could even be a mobile collector app, or a plain Mono/.NET app/service, that could get the callbacks even via a simple HTTP listener running locally, or a TcpListener for perf.). This would make OpenCover a one-of-a-kind profiler, since the only one doing this currently (AFAIK) is MS VS Ultimate, which obviously won't work on anything other than Windows (for now?).

This would also mean instant support for complex UI automation scenarios that rely on remote process automation (i.e. via Remoting or some other means) to drive the execution, making it also a prime candidate for Visual Studio Extensibility code coverage (using either MSTest or xunit.vsix extension, neither of which currently work, as elaborated on #368).

**Comment by sawilde** [comment]
I don't think what you propose is a good fit for OpenCover, OpenCover uses several tricks that would make what you propose unworkable with the current set up. 

We dynamically add two methods to a .net runtime class (I refer to them as cuckoos) to get round security restrictions in the runtime that then allow us to then use dllimport calls into the profiler itself, we then use shared memory buffers to copy data from the profiler to the host; all of this was for speed. We did originally try sockets (you can see this in the early commits) but the performance was horrendous for the amount of data we were attempting to transfer between profiler and host and we quickly changed tack.

If you want the behaviour/need as you described I suggest you should start again rather than try and make OpenCover do code coverage this way, probably using mono.cecil to rewrite the assemblies and call into an injected assembly (avoiding the profiler API altogether) that would handle all the communication to the host. If you do go the socket route I would also use something like protobuf rather than suffer the overhead of http/wcf etc.

PS I hate coverage being gathered in integration test scenarios as you describe, personally I see no value in it, if your integration test works who cares about coverage at this point; Write unit tests and only gather coverage on those unit tests.
