### ISSUE TITLE
No unit test code coverage

### ISSUE THREAD

**Issue by SavaNDragos** [OpenCover/opencover#480]
This is mostly a qustion but I didn't manage to find any other place where I can ask it.
In the case of a solution that only has DataContracts, so no unit test, is there a way to run OpenCover to get the code coverage (it should be 'none' but sometime something escapes us and you may find some functional code in a long list of properties)?

**Comment by ddur** [comment]
OpenCover instruments & covers only (by test) executed IL code. 
No tests => no execution => no coverage.

**Comment by sawilde** [comment]
In addition to @ddur's statement when you say DataContracts how are they written and used by the rest of your code? If the assembly is loaded during the tests then any applicable code will be instrumented (well have instrumentation points assigned). This applies to properties as well unless you use the `-skipautoprops` switch. So as long as the assembly is loaded at some point by your tests, either directly or because of other code that uses those DataContracts, then any new applicable code will be covered.

**Comment by SavaNDragos** [comment]
Well that is the problem they are not loaded, to address this issue I will create dinamically a test project that will refer all projects from that solution; one single test should be sufficient(enforce loading the dlls into memory); The idea is we want SonarQube to display everthing that it's not covered.

**Comment by sawilde** [comment]
okay

**Comment by SavaNDragos** [comment]
thanks guys
