### ISSUE TITLE
Mystery issue

### ISSUE THREAD

**Issue by ddur** [OpenCover/opencover#503]
I have two identical builds, 
First one failed to cover all sequences and branches at line 91
https://ci.appveyor.com/project/ddur/dbcl/build/0.90.172#L91
Visited Points 3699 of 4254 (86.95) 
Visited Branches 1147 of 1241 (92.43)
No errors reported.

I know that local test has covered 100%, so I repeated the build.
https://ci.appveyor.com/project/ddur/dbcl/build/0.90.173#L91
Visited Points 4253 of 4253 (100) 
Visited Branches 1240 of 1240 (100) 
and everything is suddenly OK.

OpenCover 4.6.434-rc

**Comment by sawilde** [comment]
It could be the last buffer of data wasn't transferred i.e. the profiled process was shutdown without Shutdown being called on the profiler object (it happens).

We used to keep everything in shared memory but in multi-threaded environments this meant there a lot of contention on the shared memory space and really affected performance.

**Comment by ddur** [comment]
Uncovered lines are tested first
https://coveralls.io/builds/4822062/source?filename=Source%2FCode%2FCollections%2FBitSetArray%2FBitSetArray.cs
Some of construction test will take 0.5G of memory.

**Comment by sawilde** [comment]
I've added a `-safemode:on` switch (this is the default and brings us back to basic behaviour where all data is written to a shared memory buffer) - those having performance issues can use `-safemode:off` to use thread based buffers. but understand that there may be some data loss.

**Comment by lanfeust69** [comment]
This could also be related to #335.
We (meaning also @Greybird and @bigmat) have serious troubles getting consistent coverage results. I think most of these is related to communication timeouts since we hit it hard on OpenCover : we use a (very) big machine (64 cores, 512G), and cover a PowerShell script that spawns up to 50 NUnit processes concurrently, some of these also having children. The total run is about 5 hours (having created a few thousands processes), but there are often some frozen processes that we must deal with in order to finish. Currently I'm trying a custom build with infinite timeouts, but for now I don't have a "clean" run to check (mostly for test environment issues).

**Comment by sawilde** [comment]
> we use a (very) big machine (64 cores, 512G), and cover a PowerShell script that spawns up to 50 NUnit processes concurrently, some of these also having children.
How about not running them concurrently? OpenCover was not designed with that in mind and I doubt we'd be able to support you effectively in that way; I am surprised it even works at all.

Instead run them in smaller batches or on a number of smaller machines and merge the results. That way if you have failures you can re-run just those rather than the whole suite. You'll probably find it is faster as well as OpenCover won't be a bottleneck.

**Comment by lanfeust69** [comment]
Actually merging is hard.

We started with this approach at first, but then the whole run would generate 200Gb of data to merge, and that's with a much coarser split, which made some NUnit fail with OutOfMemory, and a total elapsed time of more than 24h (compared to 5h now, and which also caused problems by itself since some tests don't like times around midnight, and may interfere with DB refresh, we unfortunately have too many tests relying on DB). And that's before Sonar integration takes another 24 hours to merge theses 200Gb !

And we can still re-run some parts with the previous reasonably-sized result (2Gb) as a starting point, but for that we need to know what we should re-run, which is not easy to find when the problem may be a failure to record rather than a failure of the test itself.

All in all, we're much better off now, but still not quite there. And this is the beauty of OSS : we can support ourselves :-)

**Comment by sawilde** [comment]
Have you tried other coverage tools - they all work slightly differently and may not have the limits that you are encountering with OpenCover. 

I just feel from the above description that rather than throw more power at it that you need to think differently and break it down; you are trying to use OpenCover like a large mallet and you really need to use it like a pick.

I don't know how you have split your code and tests but if you only test one module at a time i.e. `Company.Project.Thing.dll` is tested by `Company.Project.Thing.UnitTests.dll` then you can filter out all other modules; any coverage in other modules can be discarded as that is just drive-by coverage and won't add any real value and those modules should really have their own tests. Then merging is easier as you just merge file data and remove the bits of XML you don't want.

<xml>
 <node module="a"/>
</xml> 

concat with 

<xml>
 <node module="b"/>
</xml> 

becomes

<xml>
 <node module="a"/>
</xml> 
<xml>
 <node module="b"/>
</xml> 

now remove junk

<xml>
 <node module="a"/>
 <node module="b"/>
</xml> 

Of course you talk about databases so I suspect you have a lot of integration tests and this may not be feasible if your tests are too high level and you can't target your coverage to a specific module. 

Or perhaps you can - how long does the test suite take to run? Could you not run it many times but with different filters and gather coverage for limited area of your code ignoring tests that aren't applicable for those modules.

**Comment by lanfeust69** [comment]
> Have you tried other coverage tools - they all work slightly differently and may not have the limits that you are encountering with OpenCover.

We (actually _they_, I wasn't involved at that time) had a go with NCover, without that much success.

> I suspect you have a lot of integration tests

Indeed, despite a lot of efforts, we still have *way* too many tests much more at the "integration" level than "unit" level...

> how long does the test suite take to run ?

The cumulative elapsed time is a bit more than a week (without coverage), but a significant part is slowed down by db access.

Your suggestions are interesting, but would require a significant amount of work to evaluate. OTOH, we now have very decent coverage reports, even if we still lack a fair bit of consistency. Since there is a lot more elapsed time (while things are running) than real human time involved, I think it's worth pursuing our current approach, not to mention that fixing any random (and rare) issue that we have a better chance of hitting is a benefit for everyone. And I'm rather optimistic about the end result :-)

**Comment by sawilde** [comment]
> I think it's worth pursuing our current approach, not to mention that fixing any random (and rare) issue that we have a better chance of hitting is a benefit for everyone. And I'm rather optimistic about the end result :-)

I look forward to the community reaping the rewards - I still think you're mad though :)

**Comment by sawilde** [comment]
We have published the release at https://www.nuget.org/packages/OpenCover/4.6.519 and https://github.com/OpenCover/opencover/releases/tag/4.6.519
