### ISSUE TITLE
Allow concurrent executions of OpenCover

### ISSUE THREAD

**Issue by lanfeust69** [OpenCover/opencover#538]
OpenCover unregisters the profiler dll at the end of its execution, so any other instance still running, and for which a new process is created won't have this process covered (an error "Loading profiler failed during CoCreateInstance" should appear in the event log).

I wrote an alternative implementation for "User" registration that seems to work fine, but I haven't finished completely testing it, I will propose a Pull Request when done.

**Comment by sawilde** [comment]
just preregister the dlls using regsvr32 and don't use the -register switch - this is documented

**Comment by lanfeust69** [comment]
Yes, this is the alternative.

However it doesn't play very well with simple provisioning of slaves for Jenkins (or similar use), and doesn't allow using different versions of OpenCover.

**Comment by sawilde** [comment]
> However it doesn't play very well with simple provisioning of slaves for Jenkins (or similar use)

I don't see why - you can use /n:user with regsvr32 to limit to the current user. 

Since OpenCover is a COM object you can only have one registered at a time anyway

Another alternative is to use `-register:path32` or `-register:path64` if you know you are profiling a 32/64 bit process, this uses registry free loading, again this is limited to the profiler run and does not involve the registry; unfortunately you cannot register both at the same time this way as the runtime only supplies one environment variable for you to use.

**Comment by GaTechThomas** [comment]
I have been struggling with builds on a particular machine. The comment from above was a huge help:

> Another alternative is to use -register:path32 or -register:path64 if you know you are profiling a 32/64 bit process, this uses registry free loading...

After trying many suggested options, "-register-path32" was the winner.

Hopefully this helps posterity.

**Comment by Jarbasjuniorbh** [comment]
As @sawilde said: 

> unfortunately you cannot use both at the same time this way as the runtime only supplies one environment variable for you to use." I'm a bit confusing, can I use Path64 with two instances of OpenCover or not? Thanks!

**Comment by sawilde** [comment]
@Jarbasjuniorbh - you've probably tried it by now but yes you can
