### ISSUE TITLE
Unable to install via nuget due to missing assembly references for .NET

### ISSUE THREAD

**Issue by lemining** [OpenCover/opencover#541]
Hi there,

I have been using OpenCover for a while now and I really love it. (Well done!) Today I'm setting up a brand new project and whenever I try to install your stable (non RC version) I get error below.

`install-package : Could not install package 'OpenCover 4.5.3723'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or 
content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ install-package kaiseki
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand`

I have tried every version starting from 4.5 all the way to 4.6.1 and I get same error for every single one of them. Any ideas?

**Comment by sawilde** [comment]
1) try the latest version 
2) try adding it as a solution package rather than a project package i.e. it goes in the .nuget\packages.config file if you have one; these packages are usually utilities e.g. nunit.runners, reportgenerator, opencover etc. Unfortunately the package manager console does not let you install this way AFAIK so use the UI or hand edit the file.

**Comment by lemining** [comment]
Yes you were right! It worked (I used VS2013 instead of VS2015 as it seems a lot easier).

Thanks for your quick reply. Much appreciated.
