### ISSUE TITLE
Various WebSite in IIS

### ISSUE THREAD

**Issue by jesusAQCLab** [OpenCover/opencover#609]
I like measure the coverage two applications that they are run with IIS. I usually use the instruction:
opencover.console.exe  -target:C:\windows\SysWOW64\inetsrv\w3wp.exe -targetdir:C:\inetpub\wwwroot\aplicaciones\ -output:C:\Resultado.xml -register:user -targetargs:"-debug -s 4".

But, this expression only run one applications. How could you run two or more applications? I have tried with -targetargs:"-debug -s 4, 3" and it does not work.

Thank you

Regards

**Comment by pieroway** [comment]
I 2nd this question.  New feature, or just better documented hack to achieve the same goal would be appreciated.
Thanks

**Comment by sawilde** [comment]
OpenCover initially only starts one process as it has to track it to know when it has closed; it assumes that when the main process has finished then all the child processes have also completed. 

Here are somethings you can try:

1. You could just run two copies of opencover at the same time against an instance of IIS each, then use reportgenerator to merge multiple OpenCover reports into a single HTML report.
2. You could call a batch file that launches the two or more services in parallel; you may need to stick a pause on the batch file to stop it closing before you services have been tested. The first process opencover calls doesn't have to be a .NET application.
3. You could write your own launcher that you could use to control the applications under test that would could control from your test environment. 
4. Ask Microsoft to change the launch arguments of `w3wp` to allow you to launch two web applications; it's worth a try. 

That's 3 possibilities for you both to try in a few minutes; I'll discount the last one as we know that'll never happen.

NOTE: In the end the original intention for OpenCover was for unit test coverage rather than integration test scenarios like this, so running against a full-blown app / service is more of a plus.

**Comment by pieroway** [comment]
Success is always a tools problem as the end user is constantly using it in ways it was never intended. :). Thanks for the suggestions, I'll give a few a try. 
Al

**Comment by sawilde** [comment]
@jesusAQCLab @pieroway 

have you made any headway?

Shaun

**Comment by pieroway** [comment]
Not yet.  Our first priority was get it working (via the known IIS way) and then once that's running in CI, then we can look at other ways to make it work better.
And, I'm on vacation this coming week, so I wont even get close to working on these ideas until the following week, at best.  My boss thinks a few of your suggestions are worth pursuing so I'm expect I'll get to investigate and report back.
Thanks,
Al

**Comment by jesusAQCLab** [comment]
Hi, we are testing with other tools with similar functionality and it allow us to do what we want in a simple way.

Thank you.

**Comment by pieroway** [comment]
What tools? May I ask?
