### ISSUE TITLE
Are arguments "case sensitive" or not?

### ISSUE THREAD

**Issue by michael-freidgeim-webjet** [OpenCover/opencover#653]
The documentation in https://github.com/opencover/opencover/wiki/Usage and https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf
doesn't specify are argument values in filters (and other arguments)  case sensitive or not.
Please update the doc. 
If they are   case sensitive, please consider to make them case-insencitive.

### My Framework
- [ ] .NET 4.6.1
### My Environment
- [ ] Windows 10

### I have already...

- [ ] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):
- [ ] feature request

### Expected Behavior

To be documented Are arguments "case sensitive" or not?.
Make them case insensitive

### Actual Behavior

not documented

**Comment by sawilde** [comment]
The filters are case sensitive because the .net type system is case sensitive and so you may wish to distinguish between things like "Attribute" and "attribute".

I'll need a strong argument as to why this feature needs to be implemented and can't be used as-is. 

I am wary of making it case-insensitive after 5+ years because of the impact it may have on existing users.

**Comment by michael-freidgeim-webjet** [comment]
But file names are not case-sensitive.
Should I have 2 filters -[*.*Tests]* and -[*.*tests]* ?
Anyway I would appreciate if the behavior will be documented in the Usage page.
