### ISSUE TITLE
Ability to exclude special code patters from uncovered lines

### ISSUE THREAD

**Issue by LymanZerga** [OpenCover/opencover#727]
In our project we have a bunch of argument null exception statements due to fxcop rules. We do not cover all of those statements through tests. So in our coverage result overview the all over covered lines/branches are some sort of falsified due to this uncovered null argument exception.

So is there a possibility to exclude some special statements from the coverage result or uncovered lines/branches?

Example:
`if (variableName == null) throw new ArgumentNullException(nameof(variableName);`

**Comment by sawilde** [comment]
No, OpenCover does NOT instrument your source code, it works on the IL and so such exclusions are not easily identifiable nor universal. 

Write more tests.

**Comment by SteveGilham** [comment]
In this particular case, if you are using CA1062#ValidateArgumentsOfPublicMethods to statically check that you are trapping null arguments, the appropriate follow-up would be another FxCop rule that loads and rewrites the coverage file, having identified the IL patterns deemed uninteresting.  And possibly code analyser that checks that there are no `[SuppressMessage("Microsoft.Design", "CA1062#ValidateArgumentsOfPublicMethods", ...)]` attributes that would otherwise defeat the static analysis.

I have used the custom FxCop rule rewriter approach myself to edit out amongst others, things like trivial properties with conventionally like-named backing fields (from the days before auto-properties, let alone auto-properties getting dropped from coverage reports by default), and methods only containing `throw new NotImplementedException()` as respectively not worth the unit test overhead, and not  having meaningful tests as yet.

**Comment by sawilde** [comment]
@SteveGilham a very useful tip
