### ISSUE TITLE
Coverage Result different in Visual Studio 2015 and from Command Prompt (MSTest)

### ISSUE THREAD

**Issue by ravikanasagra1** [OpenCover/opencover#791]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework
.Net 4.5.2

### My Environment

Windows 7

### Expected Behavior

Coverage result should be same.

### Actual Behavior

Coverage number are coming different

### Steps to reproduce the problem:

From Visual Studio 2015, Go to OpenCoverTestExplorer -> Run all test using Cover with Open Cover. It gives below result.

![vscodecoverage](https://user-images.githubusercontent.com/19424672/35215219-9430fde8-ff89-11e7-8cd0-9a7cdfff5e66.JPG)

When I used below command line to generate Coverage report I got different coverage data.

```
"path\OpenCover.Console.exe" ^
-register:user ^
-target:"path\MSTest.exe" ^
-targetargs:"/noisolation /testcontainer:\"path\ConsoleApplication1\UnitTestProject1\bin\Debug\UnitTestProject1.dll\" /resultsfile:\"TestResult.trx\"" ^
-filter:"+[*]* -mergebyhash -skipautoprops  -output:"results.xml"
```

```
"path\ConsoleApplication1\packages\ReportGenerator.3.1.1\tools\ReportGenerator.exe" ^
-reports:"path\ConsoleApplication1\UnitTestProject1\bin\Debug\results.xml" ^
-targetdir:"ReportGenerator Output"

```
![fromcommandline](https://user-images.githubusercontent.com/19424672/35215351-fcb9a716-ff89-11e7-9cf2-287a26047faa.JPG)

Also, in Visual Studio, it says code coverage where as in report generated it says Line coverage & branch coverage. What is significance of these different coverage information and why they are different?

**Comment by SteveGilham** [comment]
OpenCover works on the granularity of program sequence points in the compiled IL, which roughly correspond to statements in the source code (the `{` and `}` punctuation from C# also appear as sequence points in debug builds -- so you can set breakpoints there -- but aren't statements as such).  A statement can cover more than one line, and there can be more than one statement per line (e.g. in a one-line LINQ expression with lambdas, where each lambda is its own thing).

Consequently the percentage of lines with (some) coverage as reported by ReportGenerator can be different from the coverage percentage of sequence points noted by OpenCover in the coverage XML that ReportGenerator used.

On the other topic, branch coverage tries to distinguish the number of paths through the code, as well as just the number of statements. To take a real -- if trivial -- example
![branch](https://user-images.githubusercontent.com/7460854/35996201-ba934a9a-0d0d-11e8-8446-48781c3a2a94.png)
This F# function has 100% line or sequence point coverage but the branch coverage is only 50%, because it is never tested with `finish` being false -- as this ReportGenerator class-level report shows.
