### ISSUE TITLE
Notable to run opencover against an application service

### ISSUE THREAD

**Issue by pcmenon1980** [OpenCover/opencover#806]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework

- [ ] .NET 2
- [ ] .NET 3.5
- [ ] .NET 4
- [ ] .NET 4.5
- [X] .NET 4.6
- [ ] .NET 4.6.1
- [ ] .NET 4.6.2
- [ ] .NET Core 1.0.0
- [ ] Something else

### My Environment

- [ ] Windows 7 or below (not truly supported due to EOL)
- [ ] Windows 8
- [ ] Windows 8.1
- [ ] Windows 10
- [ ] Windows 10 IoT Core
- [ ] Windows Server 2012
- [X] Windows Server 2012 R2
- [ ] Windows Server 2016

### I have already...

- [X] repeated the problem using the latest stable release of OpenCover.
- [X] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [ ] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

- [X] no coverage being recorded
- [ ] 32 or 64 bit support
- [ ] feature request

### Expected Behavior

Fill me in...

### Actual Behavior

Fill me in...

### Steps to reproduce the problem:

Fill me in...

Hi

OpenCover Version: 4.6.519.0

I am trying to run opencover.console.exe against an application which is running as windows service
and i entered command as:
Pls see below screen shot.... strange thing is the error thrown is showing the location c:\projects which is not even existing in the system. Can you pls help me get closer to the actual problem

![image](https://user-images.githubusercontent.com/9838060/37889745-7e1ada90-30eb-11e8-8a5b-296de8f42490.png)

I am notable to run the command successfully.

**Comment by SteveGilham** [comment]
The `C:\projects\...` paths reflect the source layout in the OpenCover build environment.

The actual exception is being thrown when OpenCover is tidying up the environment variables it injected into the service (that environment being stored in the registry key `HKEY_USERS\<service SID>\Environment`) and is failing to find one of the values that it set there.

Is your service modifying any of its environment variables?

**Comment by pcmenon1980** [comment]
its not changing anything in the environment variables apart from the usual registry updations normal to any windows applications during a fresh install

**Comment by pcmenon1980** [comment]
Does Opencover needs the windows service to be adhering to some desired registry settings...

**Comment by SteveGilham** [comment]
It shouldn't need anything special in the registry to start with.

Where the registry comes in is that the user environment (including service principals as users) is stored in that user's registry; and OpenCover has to inject a number of environment variables to switch on the profiling.  These variables,(with names matching either "Opencover_*" or "Cor*Profil*", are then cleared up after the service is stopped.
What's happening here is that when that tidying-up is being done, one of the values being tidied is not there to be deleted, which isn't expected to happen -- it's assumed to "just work".  This also means that  there's no logging on the OpenCover side to say which key or keys are affected.

While the symptom could be addressed by taking a "forgiveness rather than permission" approach of catching (and logging) every such exception, that is just sweeping the underlying cause under the carpet.  If it were possible to get a (suitably redacted) dump of the output of `System.Environment.GetEnvironmentVariables()` for your service at service start and shutdown, that might shed some light on what's going on here.
