### ISSUE TITLE
I only get the coverage of the assembly with the test classes, but not the coverage of the main assembly

### ISSUE THREAD

**Issue by mydeenali** [OpenCover/opencover#808]
Please provide the following information when submitting an issue. 

> Where appropriate replace the `[ ]` with a `[X]`

### My Framework
- [x] .NET 4.7.1
### My Environment

- [ ] Windows 7 
- [ ] Windows Server 2012 R2

### I have already...

- [ ] repeated the problem using the latest stable release of OpenCover.
- [x] reviewed the [usage guide](https://github.com/opencover/opencover/wiki/usage) and [usage document](https://github.com/opencover/opencover/blob/master/main/OpenCover.Documentation/Usage.pdf).
- [x] have looked at the opencover output xml file in an attempt to resolve the issue.
- [ ] reviewed the [current issues](https://github.com/opencover/opencover/issues) to check that the issue isn't already known.

### My issue is related to (check only those which apply):

I have couple of  test assembly.
1.The Nunit  test were passed and testResult.xml were generatored .
2.The opencover.xml file were generated
3.Based on the above step .I have executed the reportgenerator tool.The report being generated
Issue: 
The main assembly report was  not generated. But Unit Test Assembly coverage has been shown.

@note 
I have enabled the Pdb -To FULL  in the vs.Properties ->Advanced  area.

Look for you support 
![configuration](https://user-images.githubusercontent.com/1828063/38207743-714d700c-36cc-11e8-932b-adb7e6aff510.PNG)
![mainassembly not reporting](https://user-images.githubusercontent.com/1828063/38207744-7189b4f4-36cc-11e8-8072-cc896801ebe1.PNG)

- [ ] no coverage being recorded

### Expected Behavior

Main assembly coverage report needs to shown.

### Actual Behavior

Only the test assembly coverage was shown

### Steps to reproduce the problem:

Fill me in...

**Comment by SteveGilham** [comment]
You've checked the box saying you've already looked at the opencover output xml file in an attempt to resolve the issue.  In that case, you can post what, if anything, there was by way of a `<Module>` tag for your main assembly, or state that there was none.

**Comment by rajeevsoni** [comment]
@SteveGilham 
m also facing the same issue.
I am trying it out with .net version 4.7.1
Is this issue only occurring in 4.7.1 ? i have tried with 4.6.1 but there every thing is working fine.
Any help is appreciated.
Thanks in advance.

**Comment by DashAce10** [comment]
I'm actually having the same problem.  I'm using ASP.NET Core 2.0 and have gotten pretty far except that the Coverage Analysis is only being applied to the test project and not the source that I want to test.  I have provided a sample project in a zip file.  The base project is just a scaffolded ASP.NET Core project.  I added the NUnit test project separately.  I run the OpenCover exe through a batch file so just execute that.  You're going to need to modify it though. I'm using custom Environment variables for the paths.  I've modified the csproj files of both projects so that the PDBs are Full and not Portables.  A <Module> tag for WebApplication1.Controllers doesn't get created in the results.xml. This would be awesome if I could get it to work for .NET Core.  My concern is that it might not be doable in Core yet.  Any help would be appreciated.  FYI, the nuget packages folder no longer exists at the project level.  MS made changes so that it exists at the machine or user level.

[WebApplication1.zip](https://github.com/OpenCover/opencover/files/1940470/WebApplication1.zip)

**Comment by agray** [comment]
> for .NET Core. My concern is that it might not be doable in Core yet. Any help would be appreciated. FYI, the nuget packages folder no longer exists at the project level. MS made changes so that it exists at the machine or user level.

I'm using ,NET Core 2.1 and I was experiencing the same problem.  I solved it by adding `<DebugType>full</DebugType>` and `<DebugSymbols>true</DebugSymbols>` to the csproj of the code under test.
