### ISSUE TITLE
Exclude delegates and linq from code coverage

### ISSUE THREAD

**Issue by surbhi05** [OpenCover/opencover#907]
Hi Team,

I have a method that contains a linq statement, if I apply the "[ExcludeFromCodeCoverage]" attribute to the method, then all the statements are excluded except for the linq statement.

Attribute used - "[ExcludeFromCodeCoverage]" and excludebyattribute in openCover script.

### My Framework
- [X] .NET 4.6.1
### My Environment
- [X] Windows 10
### Expected Behavior
OpenCover should exclude linq and delegate statements
### Actual Behavior
OpenCover is not excluding linq and delegate statements

**Comment by Serg046** [comment]
Why should OpenCover exclude them?
Actually I was going to request similar change whitch can fit your needs too.

For example, we have some enum and method
```csharp
enum SomeEnum { First, Second }

void SomeMethod(SomeEnum someEnum)
{
    switch (someEnum)
    {
        case SomeEnum.First: ...
        case SomeEnum.Second: ...
        default: throw new NotImplementedException();
    }
}
```
We cannot cover this NotImplementedException because there is no way to provide something different from SomeEnum.First or SomeEnum.Second but we still want to have this line in order to predict future issues. What about possibility to exclude by comments like this?

```csharp
enum SomeEnum { First, Second }

void SomeMethod(SomeEnum someEnum)
{
    switch (someEnum)
    {
        case SomeEnum.First: ...
        case SomeEnum.Second: ...
        // Disable OpenCover
        default: throw new NotImplementedException();
        // Restore OpenCover
    }
}
```
@sawilde do you guys have anything to solve the issue I described?

**Comment by sawilde** [comment]
@Serg046 OpenCover does not analyse source code to do its in instrumentation and so it will not see any code comments.

There is a way to pass something other BTW you can just cast an int e.g. -1000 to `SomeEnum`

```
void Main()
{
	var x = -1000;
	Test((SomeEnum)x);
}

// Define other methods and classes here
public enum SomeEnum
{
	First,
	Second
}

void Test(SomeEnum x)
{
	switch(x)
	{
		case SomeEnum.First:
		case SomeEnum.Second:
			break;
		default:
			throw new InvalidOperationException();
	}
}
```

**Comment by sawilde** [comment]
@surbhi05 I'll add it to the defect list but frankly I am dissapointed about all the request to exclude coverage - sounds like you are trying to meet a mgmt criteria that provides no real value.

**Comment by Serg046** [comment]
Thank you Shaun, I forgot about this trick.
Anyway, there are some cases when there is no workaround.

```csharp
var someClass = GetSomeClass();
switch (someClass.SomeProp)
{
	case Class1 c: ...
	case Class2 c: ...
	default: throw new InvalidOperationException();
}

public class SomeClass
{
	public BaseClass SomeProp { get; }
}

public class BaseClass
{
    internal BaseClass()
    {
    }
}

public class Class1 : BaseClass { }
public class Class2 : BaseClass { }
```
Even if we have a setter for SomeProp we cannot create any other implementations of BaseClass because its ctor is internal. Although we can assign null value (but usually there is a check that prohibits it and throws ArgumentNullException) and check the exception. However my example doesn't contain a setter.

**Comment by sawilde** [comment]
for internal classes you can use the `InternalsVisbleTo` attribute to allow your test assemblies access to your production assemblies - https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=netframework-4.8

**Comment by Serg046** [comment]
I meant the code that you cannot control like standard or third-party libraries. For example many Expression children have internal constructors.

**Comment by sawilde** [comment]
true but if it is internal and doesn't contain your code do you care?

**Comment by Serg046** [comment]
Yes, for example I have the following method in some project
```csharp
[ExcludeFromCodeCoverage]
private void Analyze(MemberExpression expression, IMemberVisitor visitor)
{
    try
    {
        Analyze((dynamic)expression.Member, visitor);
    }
    catch (RuntimeBinderException)
    {
        throw new NotSupportedExpressionException(
            $"Ivalid MemberExpression format. Type '{expression.Member.GetType().FullName}'. Source: {expression}.");
    }
}
```
There is a way to set null for Member property by reflection but it looks awful and I decided to exclude the method. Here the attribute works good enough because the method doesn't contain anything except the handler.

**Comment by sawilde** [comment]
personally I wouldn't exclude it (I am not a fan of excluding code for the sake of coverage and I sort of regret having the ability in OpenCover) as later on another developer may extend the method and now you'll not have any feedback on the change.

If you really wanted to test it then you could do something like this

```csharp
internal static void CallAnalyze(Action action, MemberExpression expression)
{
    try
    {
	action();
    }
    catch (RuntimeBinderException)
    {
        throw new NotSupportedExpressionException(
            $"Ivalid MemberExpression format. Type '{expression.Member.GetType().FullName}'. Source: {expression}.");
    }
}

private void Analyze(MemberExpression expression, IMemberVisitor visitor)
{
	CallAnalyze(() => Analyze((dynamic)expression.Member, visitor), expression);
}
```
now you can write a test for CallAnalyze will behave the way you want when a `RuntimeBinderException` is thrown

**Comment by surbhi05** [comment]
@sawilde : I found a solution for this, I added "*CompilerGenerated*" in the "excludebyattribute" as well and now the linq and delegates are actually excluded.

**Comment by sawilde** [comment]
@surbhi05 awesome but I hope it doesn't hide anything important

**Comment by SteveGilham** [comment]
The original issue is the implementation detail of the textually nested code actually living in a separate method, often in a separate class.  Even when the nesting of a method is explicit (either a a normal F# `let` declaration of one function within another, or as per the C#7 local functions feature), one would still reasonably expect the enclosing method to "win", especially as their names are mangled, and attributes cannot be placed on local function declarations.

Excluding by `[CompilerGenerated]` is a blunt instrument because it's not applied in a usefully consistent manner
* in `async/await`, some user logic gets moved into a `[CompilerGenerated]` method, while the code injected to handle the asynchrony isn't thus marked
* not all the compiler generated methods on F# algebraic types (particularly those for equality and comparison) are thus attributed 

Explicit user-requested class level exclusions are reasonably simple to apply to these cases, as it's just a case of walking the `DeclaringType` hierarchy in the Cecil model and checking for exclusions at each level.  This also means that the containing type of explicit nested types "wins", as one would reasonably expect. Primarily, this would affect attribute-based filtering, as the name of the enclosing type is the leading substring of the name of the nested one.

As `DeclaringMethod` doesn't exist, for obvious reasons, finding surrounding methods for method level exclusions [becomes complicated](https://github.com/SteveGilham/altcover/blob/5ee0c11b2bc9005e57bb81155f5a5e33e53a1a57/AltCover/Visitor.fs#L462-L587).  To achieve it involves heuristics for unpacking compiler mangled names to get the surrounding method or type, and in some cases where the new method is in a separate synthetic class, searching the discovered containing type for uses of the contained type.  And as F#'s is not a Roslyn based compiler, the heuristics there are completely unlike those of C#.

**Comment by sawilde** [comment]
closing as it looks like the original issue was resolved by the user ignoring `CompilerGenerated`
